blank_issues_enabled: false

contact_links:
  - name: Suggest a feature
    url: https://github.com/Traffic-Studio/Intersection-Studio/discussions
    about: Suggest new features and improvements in Discussions.

  - name: Ask a question
    url: https://github.com/Traffic-Studio/Intersection-Studio/discussions
    about: Ask questions and get help in Discussions.
